### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by manodeep** [zhutchens1/g3groups#1]
Hi @zhutchens1 - congrats on getting the repo setup. I noticed that you don't have a license file associated with the repo - do you mind adding one?

(Happy to assist if you need help with choosing/adding a license)

**Comment by zhutchens1** [comment]
Hi @manodeep, great to hear from you. I'm definitely willing to add a license, but I would appreciate a recommendation on which to choose. The MIT license seems most straightforward, but I'm not sure if that is best for academic/research projects. Thanks!

**Comment by manodeep** [comment]
Yup the MIT license would be appropriate. 

(The MIT license allows anyone to re-use/adapt the repo contents to make commercial/non-commercial without any liability to the author)

**Comment by zhutchens1** [comment]
Thanks Manodeep! I've added the MIT license to the repo.
